set -g mouse on
setw -g mode-keys vi
set -g prefix C-j
unbind C-b
bind C-j send-prefix
set -g history-limit 50000

# Shell
set -g default-shell "$HOME/.nix-profile/bin/zsh"
set -g default-command "$HOME/.nix-profile/bin/zsh -l"

# Clipboard
set -g set-clipboard on

# Windows / Sessions control
bind-key -n M-Left previous-window
bind-key -n M-Right next-window
bind-key -n M-Up switch-client -p
bind-key -n M-Down switch-client -n

# Panes control
## move
bind-key -n S-Left select-pane -L
bind-key -n S-Right select-pane -R
bind-key -n S-Up select-pane -U
bind-key -n S-Down select-pane -D

## split
bind - split-window -v
bind | split-window -h

# Status bar
set -g status-interval 1
set -g status-bg "colour238"
set -g status-fg "colour255"

set -g status-right " %m/%d %H:%M:%S#[default]"
set -g status-left-length 20
set -g status-left "#[bg=colour232]Session: #S #[default]"

setw -g window-status-format " #I: #W "
setw -g window-status-current-format "#[bg=colour18,underscore] #I: #W #[default]"

set -g pane-border-status top
set -g pane-border-format " #{?pane_active,👀,}#{?window_zoomed_flag,🔍,} #{pane_current_command} | #{@pane_auth_info} "
