set -g mouse on
setw -g mode-keys vi
set -g prefix C-j
unbind C-b
bind C-j send-prefix
set -g history-limit 50000

# Windows / Sessions control
bind-key -n M-Left previous-window
bind-key -n M-Right next-window
bind-key -n M-Up switch-client -p
bind-key -n M-Down switch-client -n

# Panes control
## move
bind-key -n S-Left select-pane -L
bind-key -n S-Right select-pane -R
bind-key -n S-Up select-pane -U
bind-key -n S-Down select-pane -D

## split
bind - split-window -v
bind | split-window -h
