require("options")
require("keymaps")

require("plugins.lsp")
require("plugins.fzf")
require("plugins.git")
require("plugins.diffview")
require("plugins.octo")
require("plugins.treesitter")
require("plugins.tree")
