# History
HISTSIZE=10000
SAVEHIST=10000
HISTFILE="$HOME/.zsh_history"

# Options
setopt HIST_IGNORE_DUPS
setopt SHARE_HISTORY

# Prompt
PROMPT=$'%K{238}%F{white} %~ %F{238}%k\ue0b0 %f'

# Git branch
setopt transient_rprompt
setopt PROMPT_SUBST
autoload -Uz vcs_info

zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:git:*' stagedstr '+'
zstyle ':vcs_info:git:*' unstagedstr '*'
zstyle ':vcs_info:git:*' actionformats ' [%b|%a] '
zstyle ':vcs_info:git:*' formats $'%F{white}\ue0b2%F{green}%K{white} %c%u[%b] %f%k'

precmd() {
	vcs_info
}
RPROMPT='${vcs_info_msg_0_}'

# tmux pane border update hook
function _update_tmux_pane_info() {
	if [[ -n "$TMUX" ]]; then
		(
			local git_email=$(git config user.email 2>/dev/null || echo 'Out of Git')
			local gh_auth=$(gh auth status 2>&1 | awk '/Logged in to/{print $7}')

      # If the result is empty, it means not logged in (or not authenticated for this directory)
			if [[ -z "$gh_auth" ]]; then
				gh_auth="Not logged in"
			fi
			tmux set-option -p @pane_auth_info " ${git_email} |  ${gh_auth}" >/dev/null 2>&1
		) &!
	fi
}

add-zsh-hook chpwd _update_tmux_pane_info
_update_tmux_pane_info

# EDITOR
export EDITOR="nvim"
export VISUAL="nvim"

# pnpm
export PNPM_HOME="$HOME/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"

